apiVersion: apps/v1
kind: Deployment
metadata:
  name: udagram-users-deployment
  labels:
    app: udagram-users
spec:
  replicas: 1
  selector:
    matchLabels:
      app: udagram-users
  template:
    metadata:
      labels:
        app: udagram-users
    spec:
      containers:
      - name: udagram-users
        image: vladflore/udagram-users-api:latest
        # imagePullPolicy: Always => by default
        ports:
        - containerPort: 8080
      # restartPolicy: Always => by default
