# require the branch name to be master (note for PRs this is the base branch name)
if: branch = add-env-vars-to-configmaps
language: node_js
node_js:
  - 13

services:
  - docker

script:
  - cd udagram-frontend
  - docker build -t udagram-frontend .
  - docker tag udagram-frontend vladflore/udagram-frontend:latest
  - cd ../udagram-users-api
  - docker build -t udagram-users-api .
  - docker tag udagram-users-api vladflore/udagram-users-api:latest
  - cd ../udagram-feed-api
  - docker build -t udagram-feed-api .
  - docker tag udagram-feed-api vladflore/udagram-feed-api:latest
  - cd ../udagram-reverse-proxy
  - docker build -t udagram-reverse-proxy .
  - docker tag udagram-reverse-proxy:latest vladflore/udagram-reverse-proxy

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push vladflore/udagram-frontend:latest
  - docker push vladflore/udagram-users-api:latest
  - docker push vladflore/udagram-feed-api:latest
  - docker push vladflore/udagram-reverse-proxy