apiVersion: apps/v1
kind: Deployment
metadata:
  name: udagram-frontend-deployment
  labels:
    app: udagram-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: udagram-frontend
  template:
    metadata:
      labels:
        app: udagram-frontend
    spec:
      containers:
      - name: udagram-frontend
        image: vladflore/udagram-frontend:latest
        # imagePullPolicy: Always => by default
        ports:
        - containerPort: 8080
      # restartPolicy: Always => by default
