apiVersion: v1
kind: Service
metadata:
  name: udagram-frontend-service
  labels:
    service: udagram-frontend-svc
spec:
  selector:
    app: udagram-frontend
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: LoadBalancer