apiVersion: apps/v1
kind: Deployment
metadata:
  name: udagram-reverse-proxy-deployment
  labels:
    app: udagram-reverse-proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: udagram-reverse-proxy
  template:
    metadata:
      labels:
        app: udagram-reverse-proxy
    spec:
      containers:
      - name: udagram-reverse-proxy
        image: vladflore/udagram-reverse-proxy:latest
        # imagePullPolicy: Always => by default
        ports:
        - containerPort: 8080
      # restartPolicy: Always => by default
