apiVersion: v1
kind: Service
metadata:
  name: udagram-reverse-proxy-service
  labels:
    service: udagram-reverse-proxy-svc
spec:
  selector:
    app: udagram-reverse-proxy
  ports:
    - name: "8080"
      port: 8080
      targetPort: 80
  type: LoadBalancer